<a href="https://colab.research.google.com/github/Danieliuslog/Ugnei/blob/main/Copy_of_Dataset_1_Attendance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###
# Create a copy of this notebook, then run this cell.
# After downloading the folder, delete this cell.
###
import gdown

folder_url = "https://drive.google.com/drive/folders/1zjBLQbylffOUuldIKPn1tADsvh_jAwmI?usp=sharing"
gdown.download_folder(url=folder_url, output="attendance", quiet=False)

Retrieving folder contents

Processing file 1149hZILv0gkE_CKTC0G0WYWlWiQhs77f attendance.parquet
Processing file 1_vbtVLjSSSo9sfDcT0UAiPpmaYjxcU7R docs.md
Processing file 1N4vmsTW8pPUOHF3SeSU64Dqnh4Yc1jm7 school.parquet
Processing file 1dRXUIXcOOzByXYD6C9Nbb6zvCnFtt38d subject.parquet

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1149hZILv0gkE_CKTC0G0WYWlWiQhs77f
To: /content/attendance/attendance.parquet
100%|██████████| 93.3M/93.3M [00:00<00:00, 132MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_vbtVLjSSSo9sfDcT0UAiPpmaYjxcU7R
To: /content/attendance/docs.md
100%|██████████| 2.94k/2.94k [00:00<00:00, 8.23MB/s]
Downloading...
From: https://drive.google.com/uc?id=1N4vmsTW8pPUOHF3SeSU64Dqnh4Yc1jm7
To: /content/attendance/school.parquet
100%|██████████| 32.0k/32.0k [00:00<00:00, 17.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1dRXUIXcOOzByXYD6C9Nbb6zvCnFtt38d
To: /content/attendance/subject.parquet
100%|██████████| 8.56k/8.56k [00:00<00:00, 14.9MB/s]
Download completed

['attendance/attendance.parquet',
 'attendance/docs.md',
 'attendance/school.parquet',
 'attendance/subject.parquet']

In [ ]:
import duckdb

In [ ]:
duckdb.sql(
  """
  SELECT
    school_code,
    count(*)
    FROM 'attendance/school.parquet'
  GROUP BY school_code
  HAVING COUNT(*) > 1
  """
)

┌─────────────┬──────────────┐
│ school_code │ count_star() │
│    int64    │    int64     │
├─────────────┼──────────────┤
│   191791956 │            2 │
│   190341625 │            2 │
│   190986889 │            2 │
│   191130983 │            2 │
│   190341810 │            2 │
│   195170434 │            2 │
│   190697735 │            2 │
│   295093070 │            2 │
│   190892856 │            2 │
│   190545880 │            3 │
│   190066944 │            2 │
│   290893610 │            2 │
│   190189861 │            2 │
│   191090275 │            2 │
│   190696786 │            2 │
│   191130079 │            2 │
│   302843970 │            2 │
├─────────────┴──────────────┤
│ 17 rows          2 columns │
└────────────────────────────┘

In [ ]:
school = """
SELECT
  school_code,
  school_name,
  municipality_name
FROM 'attendance/school.parquet'
WHERE division_code IS NULL
"""
duckdb.sql(school + "LIMIT 10").show()

┌─────────────┬─────────────────────────────────────────────────┬─────────────────────┐
│ school_code │                   school_name                   │  municipality_name  │
│    int64    │                     varchar                     │       varchar       │
├─────────────┼─────────────────────────────────────────────────┼─────────────────────┤
│   190545880 │ Biržų „Aušros“ pagrindinė mokykla               │ Biržų r. sav.       │
│   191130264 │ Plungės „Saulės“ gimnazija                      │ Plungės r. sav.     │
│   191814839 │ Mažeikių „Žiburėlio“ pradinė mokykla            │ Mažeikių r. sav.    │
│   190507118 │ Švenčionių r. Adutiškio pagrindinė mokykla      │ Švenčionių r. sav.  │
│   191317260 │ Vilniaus Trakų Vokės gimnazija                  │ Vilniaus m. sav.    │
│   191709681 │ Vilniaus Jono Ivaškevičiaus jaunimo mokykla     │ Vilniaus m. sav.    │
│   290486810 │ Vilkaviškio rajono Pajevonio pagrindinė mokykla │ Vilkaviškio r. sav. │
│   303283300 │ Panevėžio Raimundo Sargūno sporto gimnazija     │ Panevėžio m. sav.   │
│   190486624 │ Vilkaviškio r. Gražiškių gimnazija              │ Vilkaviškio r. sav. │
│   191866526 │ Varėnos „Šaltinėlio“ pradinė mokykla            │ Varėnos r. sav.     │
├─────────────┴─────────────────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                   3 columns │
└─────────────────────────────────────────────────────────────────────────────────────┘

SUBJECT

In [ ]:
duckdb.sql(
  """
SELECT * FROM 'attendance/subject.parquet' ORDER BY random() LIMIT 10
  """
)

┌─────────────────┬──────────────────┬──────────────┬─────────────────────────────────────┬────────────────────────────────────┐
│    unique_id    │ electronic_diary │ subject_code │            subject_name             │          subject_name_en           │
│     varchar     │     varchar      │    int64     │               varchar               │              varchar               │
├─────────────────┼──────────────────┼──────────────┼─────────────────────────────────────┼────────────────────────────────────┤
│ becbaf13d99dfc2 │ Tamo             │        14002 │ ... (pasirenkamasis)                │ ... (elective)                     │
│ 0571045e7335828 │ Tamo             │         8301 │ Fizika                              │ Physics                            │
│ 0183db3f634454c │ NASC             │        21012 │ Kompozicija                         │ Composition                        │
│ 896f6fce4a49325 │ NASC             │         8101 │ Biologija                           │ Biology                            │
│ b441bbcd07dbe80 │ NASC             │        24087 │ Projektinė kalba                    │ Project-based language             │
│ a99bdf9b7700673 │ Tamo             │        10101 │ Technologijos                       │ Technologies                       │
│ 5d166884e37e67d │ Tamo             │         4105 │ Gimtoji kalba (vokiečių)            │ Native language (German)           │
│ 3e6b85b286b7d62 │ NASC             │        20102 │ Atlikėjo raiška (akordeonas)        │ Performer's expression (accordion) │
│ 431a6f0172bb93a │ Tamo             │         9108 │ Kompiuterinės muzikos technologijos │ Computer music technologies        │
│ 89d2b53d6a744a3 │ NASC             │        20101 │ Atlikėjo raiška                     │ Performer's expression             │
├─────────────────┴──────────────────┴──────────────┴─────────────────────────────────────┴────────────────────────────────────┤
│ 10 rows                                                                                                            5 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
duckdb.sql(
  """
  SELECT
    electronic_diary,
    subject_code,
    count(*)
  FROM 'attendance/subject.parquet'
  GROUP BY electronic_diary, subject_code
  HAVING COUNT(*) > 1
"""
)

┌──────────────────┬──────────────┬──────────────┐
│ electronic_diary │ subject_code │ count_star() │
│     varchar      │    int64     │    int64     │
├──────────────────┴──────────────┴──────────────┤
│                     0 rows                     │
└────────────────────────────────────────────────┘

In [ ]:
subject = """
SELECT
  electronic_diary,
  subject_code,
  subject_name_en
FROM 'attendance/subject.parquet'
"""

ATTENDENCE

In [ ]:
duckdb.sql(
  """
SELECT * FROM 'attendance/attendance.parquet' ORDER BY random() LIMIT 10
"""
).df()

,unique_id,report_period,school_code,division_code,student_class,subject_code,electronic_diary,student_count_nsa,student_count_diary,excused_lessons_illness,excused_lessons_other,unexcused_lessons
0,e607c7ca8437194,2023-09-01,290671780,None,9,5102,NASC,36,38,22,4,0
1,b73c144959b398c,2018-03-01,190918468,None,10,5301,NASC,12,12,4,2,0
2,5c4617166008048,2024-04-01,290469280,None,8,3002,NASC,26,10,0,1,0
3,17503812b9dba09,2021-03-01,190000894,None,3,2,NASC,120,3,1,1,0
4,55d6836cd873ec5,2022-04-01,190379992,None,7,5301,NASC,71,70,16,4,0
5,fb16feda33b7a38,2018-04-01,195474280,None,7,3,NASC,104,97,0,0,0
6,3f2229283ce3d5c,2020-11-01,191316354,None,9,11101,Tamo,10,9,0,0,0
7,9b2dd3cc38394e6,2023-12-01,190001843,None,9,22002,Tamo,87,87,27,0,0
8,aa9346998999149,2019-10-01,190004615,None,8,2,NASC,55,55,3,0,0
9,54ceb9903fbbd68,2023-01-01,190893381,None,5,8102,Tamo,18,18,25,0,0

In [ ]:
duckdb.sql(
  """
  SELECT
    report_period,
    school_code,
    subject_code,
    student_class,
    electronic_diary,
    COUNT(*)
  FROM 'attendance/attendance.parquet'
  WHERE division_code IS NULL
  GROUP BY all
  HAVING count(*) > 1
"""
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────────────┬─────────────┬──────────────┬───────────────┬──────────────────┬──────────────┐
│ report_period │ school_code │ subject_code │ student_class │ electronic_diary │ count_star() │
│     date      │    int64    │    int64     │     int64     │     varchar      │    int64     │
├───────────────┼─────────────┼──────────────┼───────────────┼──────────────────┼──────────────┤
│ 2024-03-01    │   190009014 │         8301 │             9 │ NASC             │            2 │
│ 2024-03-01    │   290558380 │         8402 │             5 │ NASC             │            2 │
│ 2023-12-01    │   190004615 │         8402 │             5 │ NASC             │            2 │
│ 2024-06-01    │   304089960 │         8301 │            10 │ NASC             │            2 │
│ 2023-11-01    │   190528589 │         8402 │             6 │ NASC             │            2 │
│ 2023-11-01    │   190193030 │         8101 │            10 │ NASC             │            2 │
│ 2024-03-01    │   190533045 │         8101 │             8 │ NASC             │            2 │
│ 2024-03-01    │   190007497 │         5101 │            10 │ NASC             │            2 │
│ 2025-01-01    │   290608520 │         4001 │             9 │ NASC             │            2 │
│ 2024-03-01    │   191316888 │         8101 │             9 │ NASC             │            2 │
│     ·         │       ·     │           ·  │             · │  ·               │            · │
│     ·         │       ·     │           ·  │             · │  ·               │            · │
│     ·         │       ·     │           ·  │             · │  ·               │            · │
│ 2024-06-01    │   190139463 │         5301 │            12 │ NASC             │            2 │
│ 2024-03-01    │   190399347 │         6001 │             9 │ NASC             │            2 │
│ 2024-09-01    │   304089960 │         5101 │             6 │ NASC             │            2 │
│ 2024-05-01    │   190342150 │         4001 │             8 │ NASC             │            2 │
│ 2024-05-01    │   190009014 │         5101 │             7 │ NASC             │            2 │
│ 2024-05-01    │   190005489 │         8402 │             5 │ NASC             │            2 │
│ 2025-01-01    │   190189676 │         6001 │            11 │ NASC             │            2 │
│ 2023-10-01    │   304089960 │         8101 │            11 │ NASC             │            2 │
│ 2024-10-01    │   302868589 │         8101 │             9 │ NASC             │            2 │
│ 2024-06-01    │   191417047 │         4108 │             1 │ NASC             │            2 │
├───────────────┴─────────────┴──────────────┴───────────────┴──────────────────┴──────────────┤
│ ? rows (>9999 rows, 20 shown)                                                      6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
duckdb.sql(
  """
  SELECT
    *
  FROM 'attendance/attendance.parquet'
  WHERE school_code = 190193030
  AND student_class = 10
  AND subject_code = 8101
  ORDER BY report_period

"""
).df()

,unique_id,report_period,school_code,division_code,student_class,subject_code,electronic_diary,student_count_nsa,student_count_diary,excused_lessons_illness,excused_lessons_other,unexcused_lessons
0,4147a481784cd19,2012-09-01,190193030,None,10,8101,NASC,42,40,2,3,0
1,fbff28ff28bf71d,2012-10-01,190193030,None,10,8101,NASC,42,40,0,8,0
2,e7f5ce30443b684,2012-11-01,190193030,None,10,8101,NASC,42,40,2,10,0
3,3ffb395cc08592a,2012-12-01,190193030,None,10,8101,NASC,42,40,3,12,0
4,9d0145aafd28687,2013-01-01,190193030,None,10,8101,NASC,40,40,13,16,0
...,...,...,...,...,...,...,...,...,...,...,...,...
135,dc0c0e9318b8e8c,2024-11-01,190193030,None,10,8101,NASC,27,27,4,1,0
136,05ea87842af413b,2024-12-01,190193030,None,10,8101,NASC,27,27,5,0,0
137,b928c90b44c8e2f,2024-12-01,190193030,None,10,8101,NASC,27,27,5,0,0
138,99a454d7e0f77ed,2025-01-01,190193030,None,10,8101,NASC,27,27,4,0,0
139,e23257de9bf6ce7,2025-01-01,190193030,None,10,8101,NASC,27,27,1,0,0

In [ ]:
attendance = """
  SELECT
    report_period,
    school_code,
    student_class,
    subject_code,
    electronic_diary,
    FIRST(student_count_diary) AS student_count,
    SUM(excused_lessons_illness) AS excused_lessons_illness,
    SUM(excused_lessons_other) AS excused_lessons_other,
    SUM(unexcused_lessons) AS unexcused_lessons
  FROM 'attendance/attendance.parquet'
  WHERE division_code IS NULL
  GROUP BY all
"""

Final query

In [ ]:
query = f"""

WITH
  attendance AS ({attendance}),
  school AS ({school}),
  subject AS ({subject})

SELECT
  school.school_name,
  school.municipality_name,
  subject.subject_name_en,
  attendance.student_class,
  attendance.report_period,
  attendance.student_count,
  attendance.excused_lessons_illness,
  attendance.excused_lessons_other,
  attendance.unexcused_lessons
FROM attendance
JOIN school ON attendance.school_code = school.school_code -- == USING (school_code)
JOIN subject on attendance.subject_code = subject.subject_code
  AND attendance.electronic_diary = subject.electronic_diary
"""
print(query)

In [ ]:
duckdb.sql(query).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,school_name,municipality_name,subject_name_en,student_class,report_period,student_count,excused_lessons_illness,excused_lessons_other,unexcused_lessons
0,Vilniaus šv. Kristoforo gimnazija,Vilniaus m. sav.,Music,10,2023-12-01,133,24.0,1.0,14.0
1,Kėdainių „Spindulio“ mokykla,Kėdainių r. sav.,Ethical education (ethics),4,2023-06-01,5,0.0,0.0,0.0
2,Vilniaus šv. Kristoforo gimnazija,Vilniaus m. sav.,Informatics,12,2024-12-01,146,46.0,6.0,35.0
3,Kauno suaugusiųjų ir jaunimo mokymo centras,Kauno m. sav.,Information technologies,9,2019-10-01,50,0.0,0.0,111.0
4,Kauno šv. Roko mokykla,Kauno m. sav.,"Foreign language (first, English)",7,2018-01-01,6,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4920497,Vilniaus Antakalnio progimnazija,Vilniaus m. sav.,World studies,2,2021-06-01,10,2.0,2.0,0.0
4920498,Klaipėdos r. Kretingalės pagrindinė mokykla,Klaipėdos r. sav.,World studies,1,2023-02-01,21,35.0,0.0,0.0
4920499,Gargždų „Kranto“ progimnazija,Klaipėdos r. sav.,World studies,4,2022-11-01,54,71.0,0.0,0.0
4920500,Panevėžio „Vilties“ progimnazija,Panevėžio m. sav.,World studies,1,2023-02-01,41,34.0,1.0,0.0
4920501,Vilniaus darželis-mokykla „Dainorėliai“,Vilniaus m. sav.,World studies,4,2022-12-01,18,0.0,0.0,22.0